export const ADD_NUMBER = 'ADD_NUMBER';
export const GET_REPOSITORIES = 'GET_REPOSITORIES';
export const ADD_SEARCH_VALUE = 'ADD_SEARCH_VALUE';
export const GET_REPOSITORIES_SUCCESS = 'GET_REPOSITORIES_SUCCESS';
export const ERROR_HANDLER = 'ERROR_HANDLER';
export const POPAP_ERROR_CHANGE = 'POPAP_ERROR_CHANGE';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const BOUNCE_CHANGE = 'BOUNCE_CHANGE';
